# This file is part of the Ebili Online System project.
# GitHub Actions workflow for deploying to GoDaddy via FTP
# Reviewed: by Lu Cab
name: Deploy to GoDaddy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # semantic version tags like v1.0.0

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set deployment version file
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "${GITHUB_REF#refs/tags/}" > DEPLOY_VERSION.txt
          else
            echo "${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)" > DEPLOY_VERSION.txt
          fi

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/node_modules/**
            **/resources/**
            **/tests/**
            **/.git/**
            **/.github/**
            **/.fleet/**
            **/.idea/**
            **/.vscode/**
            .env
            package.json
            package-lock.json
            deploy.php
            public/build
            public/hot
            public/storage
            storage/*.key
            vendor/**
          security: loose
