name: Deploy to GoDaddy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set deployment version file
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "${GITHUB_REF#refs/tags/}" > DEPLOY_VERSION.txt
          else
            echo "${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)" > DEPLOY_VERSION.txt
          fi

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/node_modules/**        # exclude dev dependencies
            **/tests/**               # exclude tests
            **/.git/**                # git internals
            **/.github/**             # GitHub Actions
            **/.idea/**               # PHPStorm config
            **/.vscode/**             # VSCode config
            *.zip                     # local build artifacts
            .env                      # keep server env manually
            deploy.php                # deployment script
            storage/*.key             # ignore local keys
          security: loose
          dangerous-clean-slate: false # only sync changed files
